[package]
name = "shipyard"
version = "1.9.1"
description = "A local-first Git client"
authors = ["RazorKode LLC"]
license = "MIT"
edition = "2021"

[lib]
name = "shipyard_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tauri-plugin-process = "2"
tauri-plugin-updater = "2"
uuid = { version = "1", features = ["v4"] }
portable-pty = "0.8"
notify = "8"
notify-debouncer-mini = "0.7"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
